if(is_proc('_msunit_')) {

proc _x_safe() {_msunit_unsupported()}
proc _print() {_msunit_unsupported()}
proc _println() {_msunit_unsupported()}
proc _sleep() {_msunit_unsupported()}
proc _assert_time() {_msunit_unsupported()}
proc _time_test() {_msunit_unsupported()}
proc _attension_time() {_msunit_unsupported()}
proc _skip_test() {_msunit_unsupported()}
proc _assert_ref_eq() {_msunit_unsupported()}
proc _assert_not_ref_eq() {_msunit_unsupported()}
proc _assert_true_obj() {_msunit_unsupported()}
proc _assert_false_obj() {_msunit_unsupported()}
proc _assert_true() {_msunit_unsupported()}
proc _assert_false() {_msunit_unsupported()}
proc _assert_null() {_msunit_unsupported()}
proc _assert_not_null() {_msunit_unsupported()}
proc _assert_equals() {_msunit_unsupported()}
proc _assert_not_equals() {_msunit_unsupported()}
proc _assert_size() {_msunit_unsupported()}
proc _assert_length() {_msunit_unsupported()}
proc _assert_empty() {_msunit_unsupported()}
proc _assert_not_empty() {_msunit_unsupported()}
proc _assert_type() {_msunit_unsupported()}
proc _assert_key_exist() {_msunit_unsupported()}
proc _assert_key_not_exist() {_msunit_unsupported()}
proc _assert_proc_array_throw() {_msunit_unsupported()}
proc _assert_closure_array_throw() {_msunit_unsupported()}
proc _assert_proc_throw() {_msunit_unsupported()}
proc _assert_closure_throw() {_msunit_unsupported()}
proc _assert_custom_fail() {_msunit_unsupported()}
proc _assert_diff_fail() {_msunit_unsupported()}
proc _assert_undiff_fail() {_msunit_unsupported()}
proc _assert_fail() {_msunit_unsupported()}
proc _restart_assert_time() {_msunit_unsupported()}
proc _get_state_test() {_msunit_unsupported()}
proc _get_module_setting() {_msunit_unsupported()}
proc _unit_get_resource() {_msunit_unsupported()}
proc _unit_get_data() {_msunit_unsupported()}

}
